[project]
name = 'nft-trading'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.SIP-010]
path = 'contracts/SIP-010.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-auction]
path = 'contracts/nft-auction.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
